### ISSUE TITLE
Create a demo TOM app that contains all the integration points required to customize your tom

### ISSUE THREAD

**Issue by jchate6** [TOMToolkit/tom_demoapp#16]
We need some location for example code that tom admin and TOM developers can use to customize their TOM.
Documentation is great, but a demo app that can also serve as a development testbed will be ideal.

- [ ] TOMToolkit/tom_base#1100
- [ ] TOMToolkit/tom_base#1101
- [ ] TOMToolkit/tom_base#745 
- [ ] TOMToolkit/tom_demoapp#1 
- [ ] TOMToolkit/tom_base#1048 
- [ ] TOMToolkit/tom_base#1083 
- [ ] Add a Harvester?
